Sort python runner safe builtins
getredash/redash pull request #5281
Opened 2020-11-21 03:37 UTC by zhongjiajie

Sort it and add unittest to avid regression

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Other

## Description

Sort it and add unittest to avid regression

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2020-11-21 05:06 UTC, zhongjiajie commented
@gabrieldutra @rauchy @rafawendel PTAL, I sorted the python runner builtins package and add unittest for it

2020-11-22 12:51 UTC, arikfr reviewed
Thank you for this, but I'm not sure if this is a behavior that needs testing?

Also, we're using Black to format the codebase and it uses double quotes.

2020-11-23 15:18 UTC, zhongjiajie commented
I add test for avoiding regression, it could be more easy to check if adding package break the order or not.
> Black to format the codebase and it uses double quotes.
And CI green, strangely

2020-11-23 15:25 UTC, zhongjiajie commented
I change to double quotes, could you please take a look? @arikfr @kravets-levko

2022-07-03 04:04 UTC, susodapop requested changes
LGTM. One nit for grammar. Happy to merge right away after.

Thank you again!

2022-07-03 04:04 UTC, susodapop commented on tests/query_runner/test_python.py
> +        assert src == sorted(src), 'Python safe_builtins package no sorted.'
```suggestion
        assert src == sorted(src), 'Python safe_builtins package not sorted.'
```

2022-07-06 11:37 UTC, susodapop commented
Thank you. CI is flaky for build / tests right now. I've checked the code out to run locally. Will merge once I've confirmed the tests pass.

2022-07-06 12:21 UTC, susodapop commented
I manually verified all tests (unit, e2e) pass and the build runs fine locally.

Thanks again for this contribution!

2022-07-06 13:18 UTC, susodapop commented
I cloned this PR so it would pass the CI build. It failed as a side-effect of being open so long. Oops.

Interesting side note: this happened in #5781, exactly 500 issues/pulls after this one was opened. If I could merge it at 11:11 UTC I would 😆

2022-07-06 13:18 UTC, closed without merging