Truncate large Databricks ODBC result sizes
getredash/redash pull request #5290
Opened 2020-12-01 22:08 UTC by christophergrant

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
This PR adds a row limiter to the Databricks query runner to limit exposure to platform instability caused by users attempting to load huge result sets, resulting in Redash Web worker crashes. The PR adds an additional parameter to the query result data which can be used by the front end to signal any warnings in the UI associated with this query result.

## Related Tickets & Documents
N/A
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2020-12-09 09:48 UTC, arikfr commented on redash/settings/__init__.py
> +DATABRICKS_ROW_LIMIT = int(os.environ.get("REDASH_DATABRICKS_ROW_LIMIT", 20000))
Let's move this definition directly into `redash.query_runner.databricks` as we do with other query runner specific settings.

2020-12-09 09:48 UTC, arikfr commented on redash/query_runner/databricks.py
> +                    )
Let's simplify the log message:

```suggestion
                    logger.warning("Truncated result set.")
```

We will have to get the context from the surrounding log message related to the execution.

2021-01-08 17:27 UTC, susodapop requested changes
This looks ready to go with one small change.

2021-01-08 17:27 UTC, susodapop commented on redash/settings/__init__.py
> +DATABRICKS_ROW_LIMIT = int(os.environ.get("REDASH_DATABRICKS_ROW_LIMIT", 20000))
```suggestion

```

2021-01-08 17:27 UTC, susodapop commented on redash/settings/__init__.py
> +DATABRICKS_ROW_LIMIT = int(os.environ.get("REDASH_DATABRICKS_ROW_LIMIT", 20000))
I see the setting was added to `databricks.py` but not removed here.

2021-01-08 17:27 UTC, susodapop commented on redash/query_runner/databricks.py
> +                    len(result_set) >= settings.DATABRICKS_ROW_LIMIT
```suggestion
                    len(result_set) >= ROW_LIMIT
```

2021-01-08 17:28 UTC, susodapop commented on redash/query_runner/databricks.py
> +                    len(result_set) >= settings.DATABRICKS_ROW_LIMIT
Since `settings` no longer includes DATABRICKS_ROW_LIMIT you need to use the constant declared in `databricks.py`

2021-01-08 21:19 UTC, susodapop approved these changes
LGTM

2021-01-08 21:20 UTC, merged