Nz support
getredash/redash pull request #5771
Opened 2022-06-18 02:06 UTC by aniket-s-kulkarni

## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
Adding a query runner to support Netezza Performance Server as a data source. 

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Manual testing included 
- connecting a variety of Netezza backends
- running individual queries
- ensuring that schema discovery is working well

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
<img width="1080" alt="New data source" src="https://user-images.githubusercontent.com/7376200/174418350-29407034-8e55-4fbc-9246-3bd3dc5abcbd.png">

<img width="908" alt="New data source " src="https://user-images.githubusercontent.com/7376200/174418379-12bcfe25-a5b6-45ed-9373-af600962fb2f.png">

2022-06-24 21:30 UTC, aniket-s-kulkarni commented
I am confused by the failing check about UI review. Do I need to add a different label for the right review team to take a look at this?

2022-07-02 18:20 UTC, susodapop requested changes
Thanks so much for this contribution. 

I requested a two small changes to avoid build issues.

I haven't tested this against an active Netezza system. But we'll take your word for it that this succeeds. Happy to merge once the requirements files are fixed.

2022-07-02 18:20 UTC, susodapop commented on requirements.txt
> +nzalchemy
Query runner dependencies belong in `requirements_all_ds.txt`. `requirements.txt` is only for Redash's own dependencies.

You can see [this article](https://redash.io/help/open-source/dev-guide/write-a-query-runner#Finishing-up) for more info.

```suggestion
```

2022-07-02 18:20 UTC, susodapop commented on requirements_all_ds.txt
> +nzpy
Mirrors what was added to `requirements.txt` originally.

```suggestion
nzpy>=1.15
nzalchemy
```

2022-07-02 18:20 UTC, susodapop commented on requirements_dev.txt
> +nzalchemy
`requirements_dev.txt` is only for development dependencies, needed for unit tests and other general development tasks. See earlier comment about where to specify query runner dependencies.

```suggestion
```

2022-07-02 18:20 UTC, susodapop commented
Our percy check is flaky right now. I've manually verified there are no UI changes that would block merging this PR.

2022-07-07 02:25 UTC, aniket-s-kulkarni commented
> Our percy check is flaky right now. I've manually verified there are no UI changes that would block merging this PR.



> Thanks so much for this contribution.
> 
> I requested a two small changes to avoid build issues.
> 
> I haven't tested this against an active Netezza system. But we'll take your word for it that this succeeds. Happy to merge once the requirements files are fixed.

Thanks @susodapop

I have addressed the review comments and 

> Thanks so much for this contribution.
> 
> I requested a two small changes to avoid build issues.
> 
> I haven't tested this against an active Netezza system. But we'll take your word for it that this succeeds. Happy to merge once the requirements files are fixed.


@susodapop thanks, yes I have addressed the review comments and resolved the conflicts. I do have access to Netezza and therefore have been able to test it out.

2022-07-07 03:23 UTC, susodapop commented
Thank you! It's nighttime GMT-5. I'll review tomorrow and follow-up with you. Huge thanks for your responsiveness! 🙏

2022-07-08 18:10 UTC, susodapop approved these changes
LGTM

2022-07-08 18:10 UTC, merged