improvement: MongoDB - JSON syntax error sent back to Client
getredash/redash pull request #6068
Opened 2023-05-29 21:40 UTC by agrawaltejas01

## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2023-05-29 21:46 UTC, agrawaltejas01 commented
[Screenshot of Client](https://drive.google.com/file/d/1KMUFJP_FhnUX-Q7iR3Td9qMtLdRL_udP/view?usp=share_link)

2023-06-16 01:37 UTC, Avey777 commented
It is already difficult to merge the code here. You have another option available:
https://github.com/RedashCommunity/redash

2023-07-06 13:48 UTC, guidopetri commented on redash/query_runner/mongodb.py
> +            return None, error.__str__()
We might want to keep the old message and just append the error message that is returned.

2023-07-06 13:50 UTC, guidopetri commented
@agrawaltejas01 thanks for your contribution! Would you mind rebasing on `master` and pushing your branch again to re-run the CI checks?

2023-07-21 07:41 UTC, junnplus requested changes

2023-07-21 07:41 UTC, junnplus commented on redash/query_runner/mongodb.py
> +            return None, error.__str__()
```suggestion
            return None, f"Invalid JSON format. {error.__str__()}"
```

2023-07-21 09:52 UTC, justinclift commented on redash/query_runner/mongodb.py
> +            return None, error.__str__()
That sounds like a good idea. :smile:

2023-07-21 13:18 UTC, merged

2023-07-21 13:40 UTC, justinclift commented
Something bizarre there.  The Codecov test when it was merged into `master` shows as a failure, even though when looking at the test details it clearly says there was no change in coverage (0.00%).

It *seems* like the Codecov bot is sometimes flaky.  That's not good. :frowning:

2023-07-21 13:47 UTC, junnplus commented
I may know the reason. Sometimes the master's test coverage results are not uploaded successfully, resulting in incorrect test coverage in the next merge report.

2023-07-21 15:29 UTC, justinclift commented
Interesting.  If it happens more than rarely, we might need to add some kind of "retry" attempt to the upload then. :smile: