Fix typo from ElasticSearch to Elasticsearch
getredash/redash pull request #6349
Opened 2023-08-06 04:44 UTC by kaibadash

## What type of PR is this? 

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

Fix typo from ElasticSearch to Elasticsearch.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [x] E2E Tests (Cypress)
- [x] Manually
    - <img width="538" alt="スクリーンショット 2023-08-06 13 43 00" src="https://github.com/getredash/redash/assets/391549/2bcc4251-ddd2-4cb8-89a1-d52d276c0960">
- [ ] N/A

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2023-08-06 10:46 UTC, konnectr commented
What is the meaning of these changes ? For me personally, it makes sense to change the qr name, but not to change the name of the class

2023-08-06 11:40 UTC, justinclift commented
It's probably for consistency.  As long as it passes CI and doesn't introduce any other problems, then this change should be ok (in my opinion).  It's making the code base "better". :smile:

2023-08-06 19:29 UTC, justinclift commented
@guidopetri @wlach Any interest in taking a look at this PR?

It *seems* pretty straight forward to me. :smile:

2023-08-06 19:35 UTC, wlach requested changes
Inclined to agree with @konnectr, changing the display string to match the product name makes sense, but I think using camelcase for the internals makes sense. Certainly doesn't seem worth the risk of breaking things.

2023-08-06 20:46 UTC, justinclift commented
Thanks @wlach, sounds like a plan.  :smile:

2023-08-06 23:40 UTC, kaibadash commented
Thank you for your review :+1: I'll fix it asap.

2023-08-28 18:07 UTC, wlach requested changes
Hey, sorry for the lateness in getting back to you on this. Unfortunately, this version has the same problem as before: we're changing the implementation (IMO unnecessary) when all that really needs to be updated is a single display string.

2023-08-28 18:07 UTC, wlach commented on redash/query_runner/elasticsearch2.py
> +        return "Elasticsearch"
This is the only change we should be keeping IMO

2023-08-30 07:11 UTC, kaibadash commented
Thank you for your review!

![Uploading スクリーンショット 2023-08-30 16.05.40.png…]()

I think both `OpenDistroSQLElasticSearch` and `XPackSQLElasticSearch` should be corrected. Should I change only `Elasticsearch` ?

2023-08-31 00:28 UTC, guidopetri commented
No, I think we can change all 3. Thanks :)

The test error is something unrelated and if you rebase your branch on `master` or merge `master` in, it should be fixed.

2023-08-31 08:21 UTC, justinclift commented
This PR confuses me.  Isn't it supposed to only be changing end user visible strings?

However, it looks like it's changing Python class names.

Oh... unless the front end is using the actual Python class name itself as a user visible string?

2023-08-31 12:11 UTC, guidopetri commented
Indeed; if you look in line 254 for example, `cls.__name__` returns the python class name. We should change that to hardcode the string in, following @wlach 's advice of not changing the actual class name.

2023-09-01 11:32 UTC, guidopetri approved these changes

2023-09-01 12:09 UTC, justinclift commented
@kaibadash Thanks for sticking with this, and sorry we kind of changed things around on you meanwhile. :sweat_smile:

2023-09-01 12:11 UTC, merged