added multiarch build
getredash/redash pull request #6577
Opened 2023-11-06 11:07 UTC by AndrewChubatiuk

## What type of PR is this? 
Build multiarch docker images

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
Added ability to create multiarch images

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [] Manually
- [ ] N/A

2023-11-06 11:55 UTC, guidopetri commented
Hey @AndrewChubatiuk ! Thanks for the PR. We've tried a arm64 build on GHA recently and it runs super long - so long, in fact, that it hits some hidden 6 hour limit for GHA and does not finish. Would you mind testing this on your own repo and potentially making changes there before we consider merging this in?

2023-11-06 12:02 UTC, guidopetri commented
Here's an example action that we already ran: https://github.com/getredash/redash/actions/runs/6546702269

I'm not sure how that was running so maybe we just did it wrong. :)

2023-11-07 02:15 UTC, guidopetri commented on Dockerfile
> -RUN npm install --global --force yarn@1.22.19
Could you explain the changes you're making to the Dockerfile here?

2023-11-07 02:15 UTC, guidopetri commented on Dockerfile
> -RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
I don't think this odbc driver works on arm64, but I'll be happy to be proven wrong.

2023-11-07 02:15 UTC, guidopetri commented on client/.babelrc
> +        "corejs": "3",
I don't understand any of the JS dependency related changes; @eradman would you mind taking a look? Are we able to change these deps to enable arm64 images?

2023-11-07 15:26 UTC, eradman commented on Dockerfile
> +  && curl "$DATABRICKS_ODBC_DRIVER_URL" --location --output /tmp/simba_odbc.zip \
This OBDC driver appears to be amd64 only

Does that conflict with removing ` if [ "$TARGETPLATFORM" = "linux/amd64" ]` above?

2023-11-09 20:48 UTC, eradman commented
This change seems to check out for me. Triggering CI tests

2023-11-09 23:46 UTC, eradman commented
The code coverage report is not relavent.

@guidopetri can you re-test a build with these changes on arm64?

2023-11-11 01:03 UTC, guidopetri commented on .github/workflows/ci.yml
> +          name: frontend
I'm not 100% clear where this `frontend` gets used in the build. Would you mind explaining? Does this also get pushed to Dockerhub as part of the `preview` image?

2023-11-19 00:28 UTC, guidopetri commented on .github/workflows/ci.yml
> +          name: frontend
How do we build this locally, then? `docker build -t redash_test .` seems to not build the frontend

2023-11-19 00:29 UTC, guidopetri requested changes
I'm unclear on what these changes are doing, and I think we need better documentation around this. How do we build things locally? What exactly is happening in the GHA build process? Why do we need to split up the frontend build?

2023-11-24 22:54 UTC, guidopetri commented
Hmm, alright. I think we should separate this into two PRs then:
- one enabling ARM64 builds (which may be slow if they're building the frontend);
- one separating the frontend build out, and making it clear how to build this locally. We should be able to run a `docker` command for this, and not depend on e.g. `yarn` being installed locally.

Does this make sense to you too? Or how do you think we should proceed?

2024-04-10 09:53 UTC, AndrewChubatiuk commented
merged alternative PR in https://github.com/getredash/redash/pull/6674

2024-04-10 09:53 UTC, closed without merging