add e6data query runner with test cases
getredash/redash pull request #6604
Opened 2023-11-16 08:31 UTC by anushae6

## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

## How is this tested?

- [X] Unit tests (pytest, jest)
- [X] E2E Tests (Cypress)
- [X] Manually
- [ ] N/A

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2023-11-16 12:12 UTC, masayuki038 commented
@anushae6 Sorry for the delay. 
Probably none of us have ever touched e6data. So all we rely on is your test results. I'm concerned that "Manually" in "How is this tested?" is not checked. Have you connected to e6data in your branch and checked the results of the query?

2023-11-16 12:12 UTC, masayuki038 commented
@justinclift @guidopetri We are discussing [python module dependencies](https://github.com/getredash/redash/discussions/6591). As a result of my checks, I don't think there is any problem in that point.　Are there any other points to check about accepting new data sources?

2023-11-16 14:41 UTC, anushae6 commented
My bad,I forgot to check that box. I have tested it manually as well. I'll attach some screenshots for the same
![e6data_datasource_addition](https://github.com/getredash/redash/assets/141826601/97ac1cc3-c486-4dd3-8996-f97b6625ad4b)
![e6data_configuration](https://github.com/getredash/redash/assets/141826601/f643f0db-4def-42d7-affc-8690a167a247)
![query_result](https://github.com/getredash/redash/assets/141826601/5f84cc0b-f9f4-4629-84b5-2fc34667c7ec)

2023-11-16 15:00 UTC, masayuki038 commented
@anushae6 Thanks! I confirmed your screenshots. Looks good.
Please give us a little time to discuss this. thank you.

2023-11-16 16:31 UTC, anushae6 commented
> @anushae6 Thanks! I confirmed your screenshots. Looks good. Please give us a little time to discuss this. thank you.

Sure, thanks!

2023-11-17 14:43 UTC, masayuki038 commented
@anushae6 I checked your updates. 

(Optional) It's even better to disassemble run_query and test parts of it.

When registering a new query_runner, it is desirable to have more test coverage. The next person who maintains this code will be helpful 😄 Of course, I think this is optional.

Please consider it if you have time. thank you.

2023-11-17 14:44 UTC, masayuki038 approved these changes

2023-11-18 14:04 UTC, anushae6 commented
> @anushae6 I checked your updates.
> 
> (Optional) It's even better to disassemble run_query and test parts of it.
> 
> When registering a new query_runner, it is desirable to have more test coverage. The next person who maintains this code will be helpful 😄 Of course, I think this is optional.
> 
> Please consider it if you have time. thank you.

Sure, I didn't add test case for run_query because I'll be patching most of the code so thought it won't be that useful. Will work on all the feedbacks and modify the PR.

2023-11-18 23:18 UTC, guidopetri requested changes
This looks reasonable to me in general. However, we definitely want to add more tests for this query runner - ideally we have at least a 90% patch coverage.

2023-11-18 23:18 UTC, guidopetri commented on pyproject.toml
> +"__init__.py" = ["F401"]
We'll want to roll back this small change :)

2023-11-18 23:18 UTC, guidopetri commented on redash/query_runner/e6data.py
> +    "DOUBLE": TYPE_INTEGER,
These don't seem right to me - should this be `TYPE_FLOAT`?

2023-11-22 12:56 UTC, anushae6 commented
Added all the requested changes, please review.

2023-11-22 13:41 UTC, masayuki038 commented
@anushae6 Thanks for adding a test for `run_query`!

2023-11-22 13:42 UTC, anushae6 commented
I'm not sure why the filter spec test is failing in e2e tests. When I ran the e2e tests on local, it passed all tests

2023-11-23 01:59 UTC, guidopetri approved these changes
@anushae6 thanks so much for your work on this PR!

2023-11-23 01:59 UTC, merged

2023-11-23 02:10 UTC, masayuki038 commented on tests/query_runner/test_e6data.py
> +    json_data, error = runner.run_query(query, user)
@anushae6 It has been merged, so please do this at another time. thank you!