Fetch collections when api key is access limited
getredash/redash pull request #6661
Opened 2023-12-13 15:55 UTC by MaxBer

When the rockset api key does not have full access to all workspaces the collection fetching fails. This PR checks for a result when fetching collection columns.

## What type of PR is this? 

- [X] Bug Fix

## Description
When the rockset api key does not have full access to all workspaces the collection fetching fails. This PR checks for a result when fetching collection columns.

Expected compatibility: Rockset production db.

## How is this tested?

- [X] Manually

1. Build image
2. Set up connection
3. Test connection
4. Go to schema overview in /queries/new

Refresh works although our API key does not have read access to all collections (across workspaces)

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2023-12-17 11:50 UTC, masayuki038 requested changes
Sorry, I didn't submit my review. I left a comment. Could you check it?

2023-12-18 12:13 UTC, MaxBer commented on redash/query_runner/rockset.py
> +                if columns:
I personally feel it doesn't make sense to show collections & tables where the user does not have access to the data?

2023-12-18 14:56 UTC, MaxBer commented on redash/query_runner/rockset.py
> +                if columns:
Calling list_workspaces & list_collections requires an access level within Rockset which yields all the workspaces available (even ones I do not have "data read" access to), and the request does not seem to provide me with any indication if I have access or not.

In this case the role has access to read data in a specific workspace but not the other ones, and when it attempts to list a collection where I do not get a result.

2023-12-18 16:01 UTC, masayuki038 approved these changes
@MaxBer Thanks for your explanation. I've understood the situation. The Rockset API specification looks a little strange, but it's not something we can change, so that's okay from my end.

I checked the test coverage in the previous commit since some uncovered code existed. Most of it wasn't covered from last time. So, I approve this MR.
https://app.codecov.io/gh/getredash/redash/commit/a8c6dd0043c06b3e90533bcc9eed8b5a4c9bf65c/blob/redash/query_runner/rockset.py

Please wait to finish the reviews for a few days.

@guidopetri @konnectr Could you check this if you have some time?

2024-01-30 03:29 UTC, guidopetri approved these changes
This looks reasonable to me too, though I'd prefer a test being added. @MaxBer any interest in adding a test?

2024-04-11 17:38 UTC, MaxBer commented
@guidopetri Sorry just saw this. We ended up going with BigQuery and shut down our Rockset instances, so.I don't really have the means to develop this further unfortunately.

2024-08-02 01:23 UTC, justinclift commented
> I don't really have the means to develop this further unfortunately.

No worries.  Lets close this PR for now.

Maybe future people using Rockset will be able to build on it anyway. :smile:

2024-08-02 01:23 UTC, closed without merging