Updated docker build
getredash/redash pull request #6912
Opened 2024-04-20 20:57 UTC by AndrewChubatiuk

## What type of PR is this? 
- upgraded cypress and axios to fix [this](https://github.com/getredash/redash/issues/6885) issue
- updated db seed function which helped to remove not needed request-cookie package
- updated cypress dockerfile to avoid viz-lib deps installation
- replaced .dockerignore with redash image specific Dockerfile.dockerignore

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2024-04-22 12:07 UTC, AndrewChubatiuk commented
@justinclift could you please review when have time?

2024-04-24 03:17 UTC, justinclift commented
@gaecoli All good, I'll take a look at this in a few hours. :smile:

2024-04-24 06:10 UTC, AndrewChubatiuk commented
> @gaecoli All good, I'll take a look at this in a few hours. 😄

@justinclift please merge this PR before other ones in a repo to speed up e2e tests execution for other pipelines

2024-04-24 14:14 UTC, justinclift commented
Sorry @AndrewChubatiuk, this will have to be a tomorrow thing instead of today.  I've run out of time and mental energy for today. :facepalm:

Unless someone else gets to it overnight of course. :smile:

2024-04-25 04:12 UTC, AndrewChubatiuk commented
@justinclift do you have time for it today?

2024-04-25 04:20 UTC, justinclift commented
Yeah.  I just finished most of the other bits I need to take care of today, so I'll grab some food now then go through this. :smile:

2024-04-25 05:44 UTC, justinclift commented on client/cypress/cypress.js
@eradman Would you have time to look over this cypress.js file?

The changes in it are more complex than I'm able to really parse atm.

The changes in the Cypress tests below though seem workable.  And it'd be good to get the Cypress pieces updated past Cypress 12.x. :smile:

2024-04-25 05:47 UTC, justinclift commented
@AndrewChubatiuk This mostly looks good.  I've asked @eradman to take a look at the most complex JS file (cypress.js) in there, as it's more complex than what I can currently grok.

> removed compose profiles

Will that affect people who run the Cypress tests manually themselves?  ie from the cli, prior to making a PR

2024-04-25 07:41 UTC, AndrewChubatiuk commented
maybe makefile should be updated as well, but current flow should not be affected

2024-04-25 08:55 UTC, AndrewChubatiuk commented
@justinclift updated makefile, so it should not affect existing user's setup

2024-04-25 12:52 UTC, eradman requested changes
From my perspective this change is too large. We need to break this update into smaller steps so that we are able to fully understand.

2024-04-25 13:36 UTC, AndrewChubatiuk commented
> From my perspective this change is too large. We need to break this update into smaller steps so that we are able to fully understand.

i can help if you have any questions. most of the changes are happening in yarn.lock, cause lot's of old packages were removed after percy upgrade

2024-04-27 04:45 UTC, AndrewChubatiuk commented
@eradman @justinclift here's a smaller PR
https://github.com/getredash/redash/pull/6931/files

2024-05-09 13:32 UTC, closed without merging